language: android
sudo: required
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

install:
install:
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - cd /tmp
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - unzip -q android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=/tmp/android-ndk-r16b
  - cd $TRAVIS_BUILD_DIR
  - .script/download_libs.sh 1

licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

script:
  - ./gradlew assembleRelease

  