language: android

matrix:
  include:
  - language: android
    android:
      components:
        - tools
        - platform-tools
        - build-tools-26.0.1
        - android-21
        - sys-img-armeabi-v7a-android-21
    env: ANDROID_ABI=armeabi-v7a API_LEVEL=android-21

  - language: android
    android:
      components:
        - tools
        - platform-tools
        - build-tools-26.0.1
        - android-24
        - sys-img-arm64-v8a-android-24
    env: ANDROID_ABI=arm64-v8a API_LEVEL=android-24

  - language: android
    android:
      components:
        - tools
        - platform-tools
        - build-tools-26.0.1
        - android-24
        - sys-img-armeabi-v7a-android-24
    env: ANDROID_ABI=armeabi-v7a API_LEVEL=android-24

before_install:
  - echo no | android create avd --force -n test -t $API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-window &


install:
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - cd /tmp
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - unzip -q android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=/tmp/android-ndk-r16b
  - cd $TRAVIS_BUILD_DIR
  - .script/download_libs.sh 1