language: android
sudo: required
android:
  components:
    - tools
    - build-tools-28.0.1
    - android-28
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

script:
  - ./gradlew assembleRelease

  